services:
  - type: web
    name: my-django-blog
    env: python
    plan: free  # or choose paid plans like starter, standard, etc.
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn shopwebsite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        fromDatabase: your-secret-key  # Or set value here directly
      - key: ALLOWED_HOSTS
        value: "my-django-blog.onrender.com"
    autoDeploy: true
    healthCheckPath: /
    disk: 512